version: '2'

services:
  db:
    environment:
      POSTGRES_DB: sdw
      POSTGRES_USER: sdw
      POSTGRES_PASSWORD: m1kUMUXmEB
      PGDATA: pg_test
    restart: always
    image: postgres
    expose:
      - "5432"
  app:
    environment:
      - DATABASE_URL = postgres://sdw:m1kUMUXmEB@db/sdw
      - DJANGO_MANAGEPY_MIGRATE = on
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8001:8000"
